wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.16
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.6.9
    start_time: 1651608491
    t:
      1:
      - 1
      - 55
      3:
      - 1
      - 19
      4: 3.6.9
      5: 0.12.16
      8:
      - 1
      - 5
batch_size:
  desc: null
  value: 64
buffer_size:
  desc: null
  value: 4096
dt:
  desc: null
  value: 0.05
epochs:
  desc: null
  value: 100
isvec:
  desc: null
  value: true
lr_nn:
  desc: null
  value: 0.001
lr_qp:
  desc: null
  value: 0.1
max_eps:
  desc: null
  value: 100
n_col:
  desc: null
  value: 5
n_vars:
  desc: null
  value: 119
nq:
  desc: null
  value: 7
nv:
  desc: null
  value: 7
q0:
  desc: null
  value:
  - 0.19634954084936207
  - -0.19634954084936207
  - 0
  - 0
  - 0
  - 0
  - 0
u_max:
  desc: null
  value:
  - 2.5
  - 2.5
  - 2.5
  - 1.5
  - 1.5
  - 1.5
  - 1.0
x_init:
  desc: null
  value:
  - 0.19634954084936207
  - -0.19634954084936207
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
